Implement Shutdown

diff --git a/.github/workflows/develop_bedbrigadedev.yml b/.github/workflows/develop_bedbrigadedev.yml
--- a/.github/workflows/develop_bedbrigadedev.yml
+++ b/.github/workflows/develop_bedbrigadedev.yml
@@ -33,6 +33,18 @@ jobs:
 
     - name: Run tests
       run: dotnet test
+      
+    - name: Perform Shutdown
+      run: |
+        response=$(curl -s -o /dev/null -w "%{http_code}" http://gregfinzer2-001-site3.ctempurl.com/api/Shutdown/PerformShutdown)
+        if [ $response -ne 200 ]; then
+          echo "Shutdown failed with status code: $response"
+          exit 1
+        fi
+      timeout-minutes: 1   
+      
+    - name: Wait for 10 seconds for PerformShutdown
+      run: sleep 10      
 
     - name: Create TmpFolder
       run: mkdir TmpFolder
@@ -49,7 +61,7 @@ jobs:
         src: ./TmpFolder/app_offline.htm
         dest: app_offline.htm
 
-    - name: Wait for 10 seconds
+    - name: Wait for 10 seconds to be offline
       run: sleep 10
       
     - name: Publish
